library(RInno)
create_app( app_name = "BTC", 
            app_dir = "BTC", 
            app_repo_url = "https://github.com/BPSModeling/BTC/tree/login-and-RInno", 
            pkgs = c("aws.signature",
                     "bcrypt",
                     "digest",
                     "poibin",
                     "doParallel",
                     "dplyr",
                     "lubridate",
                     "ggplot2",
                     "ggvis",
                     "gganimate",
                     "hashmap",
                     "htmlwidgets",
                     "magrittr",
                     "plotly",
                     "prettyR",
                     "readxl",
                     "rsconnect",
                     "RColorBrewer",
                     "scales",
                     "shiny",
                     "shinycssloaders",
                     "shinyEffects",
                     "shinythemes",
                     "shinyLP",
                     "shinyBS",
                     "shinyjs",
                     "shinyalert",
                     "shinyWidgets",
                     "shinydashboard",
                     "shinydashboardPlus",
                     "snow",
                     "doSNOW",
                     "stringr",
                     "tidyverse"), auth_token = "c9ece2da1cf7b1584fc43a3cb772d57233a8243c", overwrite = T, out_dir = "~/BP/BTC_Out")
compile_iss()